modLoader = "javafml"
loaderVersion = "[32,)"
license = "MIT"

[[mods]]
modId = "teleport"
version = "1.0.1"
displayName = "Teleport"
#updateJSONURL="http://myurl.me/" #TODO
displayURL="https://space.bilibili.com/329963941"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="teleport.png" #TODO
authors = "Stars_sea"
description = '''
相比 tp, 更加 "科学" 的传送
'''

[[dependencies.teleport]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.teleport]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.0,1.17)"
ordering = "NONE"
side = "BOTH"
